### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by Esnos33** [godotrecipes/2d_grid_movement#1]
Hi, I was learning [from your site](https://kidscancode.org/godot_recipes/3.x/2d/grid_movement/) and when I clicked on link to project file, it sends me to 404 file not found.
![obraz](https://user-images.githubusercontent.com/56300699/203836051-27a34003-46fd-4f48-b51a-d5bdf7d6c963.png)

**Comment by cbscribe** [comment]
Thanks, I've updated the link to the new repository for demo projects.
